//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalgameIndexes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalgameIndexes.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Data&gt;
        ///  &lt;Game&gt;
        ///    &lt;Company&gt;作公司（母）&lt;/Company&gt;
        ///    &lt;Subsidiary&gt;子分类&lt;/Subsidiary&gt;
        ///    &lt;Name&gt;游戏名称&lt;/Name&gt;
        ///    &lt;TranslatedName&gt;游戏译名&lt;/TranslatedName&gt;
        ///    &lt;Date&gt;发售日&lt;/Date&gt;
        ///    &lt;Translater&gt;汉化组&lt;/Translater&gt;
        ///    &lt;Progress&gt;汉化进度&lt;/Progress&gt;
        ///    &lt;NRank&gt;评分人数&lt;/NRank&gt;
        ///    &lt;Rank&gt;评分(VNDB)&lt;/Rank&gt;
        ///    &lt;SRank&gt;总评&lt;/SRank&gt;
        ///    &lt;Tags /&gt;
        ///  &lt;/Game&gt;
        ///  &lt;Game&gt;
        ///    &lt;Company&gt;UGUST（オーガスト）&lt;/Company&gt;
        ///    &lt;Subsidiary&gt;*无*&lt;/Subsidiary&gt;
        ///    &lt;Name&gt;バイナリィ?ポット -Binary Pot-&lt;/Name [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
    }
}
